import type { Block } from 'payload'

export const FeaturesFullPage: Block = {
  slug: 'featuresFullPage',
  interfaceName: 'FeaturesFullPageBlock',
  labels: { singular: 'Features — Full page', plural: 'Features full page' },
  fields: [
    {
      name: 'hero',
      type: 'group',
      required: true,
      fields: [
        { name: 'badge', type: 'text' },
        { name: 'titleHighlight', type: 'text' },
        { name: 'titleRest', type: 'text', required: true },
        { name: 'subtitle', type: 'textarea' },
        {
          name: 'tags',
          type: 'array',
          labels: { singular: 'Tag', plural: 'Tags' },
          fields: [{ name: 'text', type: 'text', required: true }],
        },
        { name: 'image', type: 'upload', relationTo: 'media' },
      ],
    },
    {
      name: 'smartHealth',
      type: 'group',
      required: true,
      fields: [
        { name: 'badge', type: 'text' },
        { name: 'title', type: 'text', required: true },
        { name: 'subtitle', type: 'textarea' },
        { name: 'sideImage', type: 'upload', relationTo: 'media' },
        { name: 'paragraph1', type: 'textarea', required: true },
        { name: 'paragraph2', type: 'textarea', required: true },
        { name: 'ctaLabel', type: 'text' },
        { name: 'ctaHref', type: 'text' },
        { name: 'ctaArrowImage', type: 'upload', relationTo: 'media' },
      ],
    },
    {
      name: 'powerfulFeatures',
      type: 'group',
      required: true,
      fields: [
        { name: 'badge', type: 'text' },
        { name: 'title', type: 'text', required: true },
        { name: 'subtitle', type: 'textarea' },
        {
          name: 'cards',
          type: 'array',
          minRows: 1,
          labels: { singular: 'Feature card', plural: 'Feature cards' },
          fields: [
            { name: 'icon', type: 'upload', relationTo: 'media' },
            { name: 'title', type: 'text', required: true },
            { name: 'description', type: 'textarea', required: true },
          ],
        },
      ],
    },
    {
      name: 'realWorld',
      type: 'group',
      required: true,
      fields: [
        { name: 'pillLabel', type: 'text' },
        { name: 'pillIconClass', type: 'text', defaultValue: 'fa-bolt' },
        { name: 'title', type: 'text', required: true },
        { name: 'subtitle', type: 'textarea' },
        {
          name: 'steps',
          type: 'array',
          minRows: 1,
          labels: { singular: 'Timeline step', plural: 'Timeline steps' },
          fields: [
            { name: 'iconClass', type: 'text', required: true },
            { name: 'title', type: 'text', required: true },
            { name: 'body', type: 'textarea', required: true },
            { name: 'aosDelay', type: 'number' },
          ],
        },
        { name: 'sideImage', type: 'upload', relationTo: 'media' },
        { name: 'floatCardTitle', type: 'text' },
        { name: 'floatCardSubtitle', type: 'text' },
      ],
    },
    {
      name: 'secureData',
      type: 'group',
      required: true,
      fields: [
        { name: 'badge', type: 'text' },
        { name: 'title', type: 'text', required: true },
        { name: 'subtitle', type: 'textarea' },
        { name: 'image', type: 'upload', relationTo: 'media' },
        { name: 'paragraph1', type: 'textarea', required: true },
        { name: 'paragraph2', type: 'textarea', required: true },
        {
          name: 'items',
          type: 'array',
          minRows: 1,
          labels: { singular: 'Highlight', plural: 'Highlights' },
          fields: [
            { name: 'icon', type: 'upload', relationTo: 'media' },
            { name: 'title', type: 'text', required: true },
          ],
        },
      ],
    },
    {
      name: 'healthTracking',
      type: 'group',
      required: true,
      fields: [
        { name: 'badge', type: 'text' },
        { name: 'titleLine1', type: 'text', required: true },
        { name: 'titleLine2', type: 'text' },
        { name: 'subtitle', type: 'textarea' },
        { name: 'productBackground', type: 'upload', relationTo: 'media' },
        { name: 'trackImage', type: 'upload', relationTo: 'media' },
        { name: 'overlayBadgeAi', type: 'upload', relationTo: 'media' },
        { name: 'overlayBadgeAlert', type: 'upload', relationTo: 'media' },
        {
          name: 'items',
          type: 'array',
          minRows: 1,
          labels: { singular: 'Tracking highlight', plural: 'Tracking highlights' },
          fields: [
            { name: 'icon', type: 'upload', relationTo: 'media' },
            { name: 'title', type: 'text', required: true },
          ],
        },
      ],
    },
    {
      name: 'appSection',
      type: 'group',
      required: true,
      fields: [
        { name: 'backgroundImage', type: 'upload', relationTo: 'media' },
        { name: 'badge', type: 'text' },
        { name: 'title', type: 'textarea', required: true },
        {
          name: 'bullets',
          type: 'array',
          minRows: 1,
          labels: { singular: 'Bullet', plural: 'Bullets' },
          fields: [{ name: 'text', type: 'text', required: true }],
        },
        { name: 'mockupImage', type: 'upload', relationTo: 'media' },
      ],
    },
    {
      name: 'faq',
      type: 'group',
      required: true,
      fields: [
        { name: 'heading', type: 'text', defaultValue: 'FAQs' },
        {
          name: 'items',
          type: 'array',
          minRows: 1,
          labels: { singular: 'FAQ item', plural: 'FAQ items' },
          fields: [
            { name: 'question', type: 'text', required: true },
            { name: 'answer', type: 'textarea', required: true },
          ],
        },
      ],
    },
  ],
}
